### ISSUE TITLE
Creating Rule does not commit to firewall 

### ISSUE THREAD

**Issue by ruimoreira** [PaloAltoNetworks/ansible-role-paloaltonetworks#2]
Hello , 

Using the following task in a playbook , despite the commit: true flag being set the commit is never executed, and I have to manually log in to the panorama appliance and commit . 

  - name: permit ssh to 1.1.1.1
          panos_security_rule:
            ip_address: "XX.XX.XX.XX"
            password: "SECUREPASSWORD}"
            rule_name: 'SSH permit'
            description: 'SSH rule '
            source_zone: ['any']
            destination_zone: ['any']
            source_ip: ['any']
            source_user: ['any']
            destination_ip: ['1.1.1.1']
            category: ['any']
            application: ['ssh']
            service: ['application-default']
            hip_profiles: ['any']
            action: 'allow'
            operation: 'add'
            commit: true
            devicegroup: 'testgroup'
  roles:
        - role: PaloAltoNetworks.paloaltonetworks

we are currently using panorama version 7.1.0.
ansible --version
ansible 2.4.1.0

**Comment by ivanbojer** [comment]
If this is still an issue please re-open it here:
https://github.com/PaloAltoNetworks/ansible-pan/issues
